# Generated by Django 3.2 on 2022-07-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_company_name', models.CharField(max_length=220)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('clint_address', models.CharField(max_length=220)),
                ('client_city', models.CharField(blank=True, max_length=220, null=True)),
                ('client_state', models.CharField(blank=True, max_length=220, null=True)),
                ('client_zip', models.CharField(blank=True, max_length=50, null=True)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('client_birthdate', models.DateTimeField(blank=True, null=True)),
                ('client_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('pdffile', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clients')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.invoices')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
